# Generated by Django 5.2.8 on 2025-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
    ]
