# Generated by Django 5.0 on 2025-11-11 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa'), ('chambre', 'Chambre')], max_length=20, verbose_name='Type')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit')),
                ('capacite_max', models.IntegerField(verbose_name='Capacité maximum')),
                ('nombre_chambres', models.IntegerField(default=1, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.IntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de la photo')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('cuisine', models.BooleanField(default=False, verbose_name='Cuisine')),
                ('animaux', models.BooleanField(default=False, verbose_name='Animaux acceptés')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Logement',
                'verbose_name_plural': 'Logements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
