# Generated by Django 5.0 on 2025-11-11 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='logement',
            name='hote',
            field=models.ForeignKey(limit_choices_to={'role': 'hote'}, on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='logements.logement'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('reservation',)},
        ),
    ]
