# Generated by Django 5.0 on 2025-11-11 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_voyageurs', models.IntegerField(verbose_name='Nombre de voyageurs')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message du client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_client', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='logements.logement')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
